from gui_cluster_configuration.parameter_frames.EnumClusteringParameter import create_enum_frame
from gui_cluster_configuration.parameter_frames.SliderClusteringParameter import create_slider_frame
from gui_cluster_configuration.parameter_frames.BooleanClusteringParameter import create_boolean_frame
